// Generated by CoffeeScript 1.7.1
(function() {
  var dirname, engine, extname, fs, glob, handlebars, isAbsolute, join, resolve, _, _ref;

  fs = require('fs');

  _ref = require('path'), join = _ref.join, extname = _ref.extname, dirname = _ref.dirname, resolve = _ref.resolve;

  handlebars = require('handlebars');

  _ = require('underscore');

  glob = require('glob');

  module.exports = engine = (function() {
    var self, _settings;

    self = engine;

    _settings = {
      extname: '.hbs',
      useLayout: true,
      layout: 'layout',
      partials_dir: null,
      layout_dir: null,
      helpers: {}
    };

    engine.get = function(name) {
      return _settings[name];
    };

    engine.set = function(name, value) {
      var k, sets, v, _results;
      sets = {};
      if (typeof name === 'string' && (value != null)) {
        sets[name] = value;
      } else if (typeof name === 'object') {
        sets = name;
      } else {
        return this;
      }
      _results = [];
      for (k in sets) {
        v = sets[k];
        _results.push(_settings[k] = v);
      }
      return _results;
    };

    function engine(path, options, fn) {
      var that;
      that = this;
      options.fileName = path;
      if (options.layout !== false && self.get('useLayout')) {
        options.layout = self.get('layout');
      }
      if (options.partials == null) {
        options.partials = [];
      }
      glob(join(self.get('partials_dir'), '**', '*' + extname(path)), function(err, files) {
        options.partials.concat(files);
        return that.read_partials_and_layout(path, options, function(err) {
          if (err) {
            return fn(err);
          }
          return that.read(path, options, function(err, str) {
            if (err) {
              return fn(err);
            }
            return that.render(str, options, fn);
          });
        });
      });
    }

    engine.prototype.render = function(str, options, fn) {
      var helper, helpers, name, partial, partials, template;
      partials = options.partials;
      helpers = options.helpers;
      for (name in partails) {
        partial = partails[name];
        handlebars.registerPartial(name, partial);
      }
      for (name in helpers) {
        helper = helpers[name];
        handlebars.regitserHelper(name, helper);
      }
      if (options.layout != null) {
        handlebars.registerPartial('yield', str);
        template = handlebars.compile(layout);
      } else {
        template = handlebars.compile(str);
      }
      return fn(null, template(options));
    };

    engine.prototype.read_partials_and_layout = function(path, options, fn) {
      var file_ext, layout, names, next, partials, that;
      if ((options.partials == null) && (options.layout == null)) {
        return fn(null);
      }
      that = this;
      partials = options.partials;
      file_ext = extname(path || self.get('extname'));
      options.partials = {};
      names = Array.isArray() ? partials : Object.keys(partials);
      if (options.layout != null) {
        layout = extname(options.layout === file_ext) ? options.layout : options.layout + file_ext;
        if (!isAbsolute(layout)) {
          layout = join(self.get('layout_dir'), layout);
        }
      }
      next = function(index) {
        var file, name;
        if (index === names.length) {
          return fn(null);
        }
        name = names[index];
        if (!isAbsolute(name)) {
          file = join(dirname(path), name + extname(path));
        }
        return that.read(file, options, function(err, str) {
          if (err) {
            return fn(err);
          }
          options.partials[name] = str;
          return next(index++);
        });
      };
      if (layout != null) {
        return this.read(layout, options, function(err, str) {
          if (err) {
            return fn(err);
          }
          options.layout = str;
          return next(0);
        });
      } else {
        return next(0);
      }
    };

    engine.prototype.read = function(path, options, fn) {
      return fs.readFile(path, 'utf8', function(err, str) {
        if (err) {
          return fn(err);
        }
        if (str[0] === '\uFEFF') {
          str = str.substr(1);
        }
        return fn(null, str);
      });
    };

    return engine;

  })();

  isAbsolute = function(path) {
    if ('/' === path[0]) {
      return true;
    }
    if (':' === path[1] && '\\' === path[2]) {
      return true;
    }
    if ('\\\\' === path.substring(0, 2)) {
      return true;
    }
    return false;
  };

}).call(this);
