// Generated by CoffeeScript 1.9.0
(function() {
  var HbsView, View,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  View = require('express/lib/view');

  module.exports = HbsView = (function(_super) {
    __extends(HbsView, _super);

    function HbsView(name, options) {}

    HbsView.prototype.lookup = function(path) {};

    HbsView.prototype.render = function(options, fn) {};

    return HbsView;

  })(View);

}).call(this);
